version: "3"
services:
  soapysdr:
    image: ghcr.io/smrqdt/docker-soapysdr:main
    container_name: soapysdr
    environment:
      SOAPY_REMOTE_IP_ADDRESS: "[::]"
      SOAPY_REMOTE_PORT: 55132
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/rtlsdr/:/dev/rtlsdr/
    network_mode: host
    # ports:
    #   - 55132:55132
    restart: unless-stopped
